"""init_models

Revision ID: 268229712326
Revises: 
Create Date: 2026-04-22 16:26:26.966569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = '268229712326'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family', sa.String(length=50), nullable=False, comment='墙柜一体 / PET门板 / 吸塑门板'),
    sa.Column('model_no', sa.String(length=50), nullable=False, comment='MX-A01'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='平板门型'),
    sa.Column('description', sa.Text(), nullable=True, comment='门型描述'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='门板 / 柜体 / 配件'),
    sa.Column('image_urls', postgresql.ARRAY(sa.Text()), nullable=True, comment="['minio://door/mx-a01.png']"),
    sa.Column('text_embedding', Vector(1024), nullable=True, comment='BGE-M3 embedding'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_family'), 'products', ['family'], unique=False)
    op.create_index(op.f('ix_products_model_no'), 'products', ['model_no'], unique=False)
    op.create_table('text_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_doc', sa.String(length=100), nullable=True, comment='来源文档文件名'),
    sa.Column('page_no', sa.Integer(), nullable=True, comment='页码'),
    sa.Column('chunk_type', sa.String(length=20), nullable=True, comment='rule / process / description / pricing_note'),
    sa.Column('content', sa.Text(), nullable=False, comment='文本内容'),
    sa.Column('embedding', Vector(1024), nullable=True, comment='BGE-M3 embedding'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_vectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False, comment='minio://...'),
    sa.Column('image_type', sa.String(length=20), nullable=True, comment='door_style / color_chip / effect'),
    sa.Column('clip_embedding', Vector(512), nullable=True, comment='CLIP embedding'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_variants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=50), nullable=False, comment='咖啡灰'),
    sa.Column('color_code', sa.String(length=20), nullable=True, comment='色卡编号'),
    sa.Column('substrate', sa.String(length=50), nullable=False, comment='ENF级实木颗粒板'),
    sa.Column('thickness', sa.Integer(), nullable=False, comment='18 (mm)'),
    sa.Column('unit_price', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='精确到分'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='计价单位'),
    sa.Column('spec', sa.JSON(), nullable=True, comment='其他规格参数'),
    sa.Column('is_standard', sa.Boolean(), nullable=False, comment='是否标准品'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注（非标说明等）'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_variants')
    op.drop_table('image_vectors')
    op.drop_table('text_chunks')
    op.drop_index(op.f('ix_products_model_no'), table_name='products')
    op.drop_index(op.f('ix_products_family'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
